server:
  port: 7912

spring:
  cloud:
    consul:
      discovery:
#        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
#        healthCheckPath: ${management.context-path}/health
        healthCheckInterval: 5s
        service-name: consul-two
        tags: foo=bar, baz
      host: localhost
      port: 8500
  application:
    name: consul-two

feign:
  hystrix:
    enabled: true