server:
  port: 7910
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
#    serviceUrl:
#      defaultZone: http://127.0.0.1:6868/eureka/
#    instance:   # 让客户端定时刷新，能发现客户端是否在线
#      lease-renewal-interval-in-seconds: 1
#      lease-expiration-duration-in-seconds: 2

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: zuul-server

zuul:
  routes:
    apia:
      path: /api-a/**
      serviceId: client-order
    apib:
      path: /api-b/**
      serviceId: client-hystrix

