server:
  port: 7911

spring:
  cloud:
    consul:
      discovery:
#        instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
#        healthCheckPath: ${management.context-path}/health
        healthCheckInterval: 5s
        tags: foo=bar, baz
        service-name: consul-three
      host: 10.43.2.188
      port: 8500
  application:
    name: consul-three