server:
  port: 6868 #服务端口


eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: false        #是否从Eureka中获取注册信息 serviceUrl: #Eureka客户端与Eureka服务端进行交互的地址
    register-with-eureka: false
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/

spring:
  application:
    name: eureka-server