server:
  port: 7901
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6868/eureka/
    instance:   # 让客户端定时刷新，能发现客户端是否在线
      leaseRenewalIntervalInSeconds: 1
      leaseExpirationDurationInSeconds: 2

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: client-book

client-order:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule  # 这里可以指定负载均衡的算法策略
