server:
  port: 7902
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:6868/eureka/
    instance:   # 让客户端定时刷新，能发现客户端是否在线
      lease-renewal-interval-in-seconds: 1
      lease-expiration-duration-in-seconds: 2

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: client-order
